# Generated by Django 5.0.6 on 2024-06-11 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertoken',
            old_name='acquired_at',
            new_name='date_added',
        ),
        migrations.AddField(
            model_name='token',
            name='token_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
