# Generated by Django 5.0.6 on 2024-06-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0002_rename_acquired_at_usertoken_date_added_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='fully_diluted_market_cap',
        ),
        migrations.RemoveField(
            model_name='token',
            name='market_cap',
        ),
        migrations.RemoveField(
            model_name='token',
            name='market_cap_dominance',
        ),
        migrations.RemoveField(
            model_name='token',
            name='percent_change_1h',
        ),
        migrations.RemoveField(
            model_name='token',
            name='percent_change_24h',
        ),
        migrations.RemoveField(
            model_name='token',
            name='percent_change_7d',
        ),
        migrations.RemoveField(
            model_name='token',
            name='price',
        ),
        migrations.RemoveField(
            model_name='token',
            name='volume_24h',
        ),
        migrations.RemoveField(
            model_name='token',
            name='volume_change_24h',
        ),
        migrations.AddField(
            model_name='token',
            name='quote',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
