# Generated by Django 5.0.6 on 2024-06-12 06:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='users',
            field=models.ManyToManyField(related_name='tokens', through='tokens.UserToken', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='token',
            name='symbol',
            field=models.CharField(max_length=20),
        ),
    ]
