# Generated by Django 5.0.6 on 2024-06-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0004_alter_usertoken_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='users',
        ),
        migrations.AlterField(
            model_name='token',
            name='symbol',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
