# Generated by Django 5.0.6 on 2024-06-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0006_token_users_alter_token_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token_id',
            field=models.IntegerField(default=0),
        ),
    ]
